config/routes.rb
Rails.application.routes.draw do
  resources :categories
  root 'recipes#index'
  resources :recipes do
    member do
      get :tags
      post :tag_add
      post :tag_remove
    end
  end

  resources :tags do
    member do
      get :recipe_list
    end
  end

  resources :pantry_items do
    member do
      get :tags
      post :tag_add
      post :tag_remove
    end
  end

  resources :meal_plans do
    member do
      post :update_finished
      get :grocery_list
    end
  end

  resources :meal_plan_recipe_items

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/recipe.rb
class Recipe < ApplicationRecord
	#make sure each attribute is entered
	validates :name, presence: true, uniqueness: {case_sensitive: false}
	validates :ingredients, presence: true
	validates :directions, presence: true
	has_many :meal_plan_recipe_items

	RECIPE_STATUS = ['Not tried', 'In the works', 'Finalized']
	validates :recipe_status, presence: true, inclusion: RECIPE_STATUS

	#a recipe can have many tags and a tags belong to many recipes
	has_and_belongs_to_many :tags

	if Rails.env.development? or Rails.env.testing?
		scope :recipe_contains, -> (name) {where("name like ?", "%#{name}%")}
		scope :ingredients_contains, -> (ingredients) {where("ingredients like ?",
			"%#{ingredients}%")}
	else
		scope :recipe_contains, -> (name) {where("name ilike ?", "%#{name}%")}
		scope :ingredients_contains, -> (ingredients) {where("ingredients ilike ?",
			"%#{ingredients}%")}
	end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
#before any of these methods are run, this before_action is run to declare
#an instance of the controller to then pass along
before_action :set_recipe, only: [:show, :edit, :update, :destroy]
helper_method :sort_column, :sort_direction

  #GET /recipes/new
  def new
  	@recipe = Recipe.new
  end

  #GET /recipes/1
  def show
  end

  #POST /recipes
  def create
  	@recipe = Recipe.new(recipe_params)
    #debugger
    if @recipe.save
      #flash[:success] = "Recipe Added!"
      redirect_to @recipe
    else
      render 'new'
    end
  end

  #GET /recipes/1/edit
  def edit
  end

  #PATCH /recipes/1
  def update
    if @recipe.update(recipe_params)
      flash[:success] = "Recipe Updated!"
      redirect_to @recipe
    else
      render 'edit'
    end
  end

  #GET /recipes
  def index
    @recipes = Recipe.order("UPPER(#{sort_column}) #{sort_direction}")
    @recipes = @recipes.paginate :page => params[:page], :per_page => 30
    @recipes = @recipes.recipe_contains(params[:recipe_contains]) if params[:recipe_contains].present?
    @recipes = @recipes.ingredients_contains(params[:ingredients_contains]) if params[:ingredients_contains].present?
  end

  #DELETE /recipes/1
  def destroy
    @recipe.destroy
    flash[:danger] = "Recipe Deleted!"
    redirect_to recipes_path
  end

  #GET /recipes/1/tags
  def tags
    @recipe = Recipe.find(params[:id])
    @tags = @recipe.tags.order("name")
  end

  # POST /recipes/1/tag_add?tag_id=2
  def tag_add
    @recipe = Recipe.find(params[:id])
    @tag = Tag.find(params[:tag])
    @recipe.tags << @tag
    redirect_to action: "tags", id: @recipe
  end

  # POST /recipes/1/tag_remove?tags[]=
  def tag_remove
    @recipe = Recipe.find(params[:id])
    tag_ids = params[:tags]

    if tag_ids.any?
      tag_ids.each do |tag_id|
        tag = Tag.find(tag_id)
        logger.info "Removing student from tag #{tag.id}"
        @recipe.tags.delete(tag)
      end
    end
    redirect_to action: "tags", id: @recipe
  end

  private
  	def recipe_params
  		params.require(:recipe).permit(:name, :ingredients, :directions,
        :notes, :source, :recipe_status)
  	end

    def set_recipe
      @recipe = Recipe.find(params[:id])
    end

    def sortable_columns
      ["Name", "Source"]
    end

    def sort_column
      sortable_columns.include?(params[:column]) ? params[:column] : "name"
    end

    def sort_direction
      %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
    end
end

app/helpers/recipes_helper.rb
module RecipesHelper
  def source_name (source_link)
    if source_link != nil
      if source_link.include? "www."
        source_link[source_link.index(".")+1..source_link.index(".",source_link.index(".")+1)-1]
      elsif source_link.include? "http"
        source_link[source_link.index("//")+"//".length..source_link.index(".")-1]
      else
        source_link
      end
    end
  end

  def sort_link(column, title = nil)
    title ||= column.titleize
    direction = column == sort_column && sort_direction == "asc" ? "desc" : "asc"
    icon = sort_direction == "asc" ? "glyphicon glyphicon-chevron-up" :
      "glyphicon glyphicon-chevron-down"
    icon = column == sort_column ? icon : ""
    link_to "#{title} <span class='#{icon}'></span>".html_safe, {column: column, direction: direction}
  end
end

app/views/recipes/_form.html.erb
<div class="row">
  <div class="span6 offset3">
		<%= form_for (recipe) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>
			<%= f.label :name %>
			<%= f.text_field :name, class: 'form-control'%>
			<br>
			<%= f.label :ingredients %>
			<%= f.text_area :ingredients, rows: "10", class: 'form-control' %>
			<br>
			<%= f.label :directions %>
			<%= f.text_area :directions, rows: "10", class: 'form-control' %>
			<br>
      <%= f.label :notes %>
      <%= f.text_area :notes, rows: "5", class: 'form-control' %>
      <br>
      <%= f.label :source %>
      <%= f.text_field :source, class: 'form-control' %>
      <br>
      <%= f.label :recipe_status %>
      <%= f.select :recipe_status, Recipe::RECIPE_STATUS, class: 'form-control' %>
      <br><br>
			<%= f.submit button + " Recipe", class: "btn btn-large btn-primary" %>
		<% end %>
	</div>
</div>

app/views/recipes/edit.html.erb
<h1>Recipe Edit</h1>

<%= render 'form', recipe: @recipe, button: "Update" %>

app/views/recipes/index.html.erb
<h1>Recipes</h1>
<h3><%=link_to 'Add a New Recipe', new_recipe_path %></h3>
<br>
<%= form_tag(recipes_path, :method => "get") do %>
    <%= text_field_tag :recipe_contains, params[:recipe_contains],
        placeholder: "Search Recipe Name" %>
    <%= text_field_tag :ingredients_contains, params[:ingredients_contains],
        placeholder: "Search Ingredients" %>
    <%= submit_tag "Search", :name => nil %>
<% end %>
<br>

<table class="table table-bordered">
  <thead>
    <tr>
      <th><%= sort_link "Name" %></th>
      <th><%= sort_link "Source" %></th>
      <th>Recipe Status</th>
      <th>Tags</th>
    </tr>
  </thead>

  <tbody>
    <% @recipes.each do |recipe| %>
    <tr>
      <td><%= link_to recipe.name, recipe %></td>
      <td><%= source_name(recipe.source) %></td>
      <td><%= recipe.recipe_status %></td>
      <td>
        <%= recipe.tags.collect {|c| c.name}.join('<br>').html_safe %>
        </td>
    </tr>
    <% end %>
  </tbody>
</table>
<%= will_paginate %>

<% if @recipes.count != Recipe.count %>
  <%= link_to "All Recipes", recipes_path %>
<% end %>

app/views/recipes/new.html.erb
<h1>New Recipe</h1>

<%= render 'form', recipe: @recipe, button: "New" %>

app/views/recipes/show.html.erb
<div class = "recipe-name">
	<h1>
		<%= @recipe.name %>
	</h1>
</div>

<div id = "contentbox">
	<div class = "ingredients">
		<h2>Ingredients</h2>
			<%= simple_format(@recipe.ingredients) %>
		<br>
	</div>

	<div class = "directions">
		<h2>Directions</h2>
			<%= simple_format(@recipe.directions) %>
		<br>
	</div>
</div>

<div class = "notes">
	<h2>Notes</h2>
		<%= @recipe.notes %>


<%if @recipe.source != nil %>
	<h3>Source</h3>
	<%= link_to source_name(@recipe.source), @recipe.source %>
<% end %>
<br>

<h2>Tags</h2>
	<% if @recipe.tags.empty? %>
		<p>There are no recipe tags</p>
	<% else %>
		<% @recipe.tags.each do |tag| %>
			<%= tag.name %><br>
		<% end %>
	<% end %>

<h3>Recipe Status</h3>
	<%= @recipe.recipe_status %>
<br>
</div>

<br>
<br>
<%= button_to 'Add to Meal Plan', meal_plan_recipe_items_path(recipe_id: @recipe) %>


<footer class = "footer">
	<nav>
		<ul>
			<li><%= link_to 'Back', recipes_path %></li>
			<li><%= link_to 'Edit Recipe', edit_recipe_path(@recipe) %></li>
			<li><%= link_to 'Add/Edit Tags', tags_recipe_path(@recipe) %></li>
		</ul>
	</nav>
</footer>

app/views/recipes/tags.html.erb
<h1><%=@recipe.name%>'s Tags</h1>

<h3>Remove Tags</h3>
<% if @tags.count > 0 then %>
  <%= form_tag (tag_remove_recipe_path(@recipe)) do %>
    <table>
      <thead>
        <th>Tag</th>
        <th>Remove?</th>
      </thead>
      <tbody>
        <% @tags.each do |tag| %>
        <tr>
          <td><%=tag.name %></td>
          <td><%= check_box_tag "tags[]", tag.id %></td>
        </tr>
        <% end %>
      </tbody>
    </table>
  <br>
  <%= submit_tag "Remove Tag(s)" %>
  <% end %>
<% else %>
  <p>No tags yet</p>
<% end %>

<h3>Add Tags</h3>
<% if @recipe.tags.count < Tag.count then %>
  <%= form_tag(tag_add_recipe_path(@recipe)) do %>
    <%= select_tag(:tag, options_from_collection_for_select(Tag.all.order("name") - @recipe.tags, :id, :name)) %>
    <%= submit_tag "Add Tag" %>
  <% end %>
<% else %>
  <p>This recipe has all tags</p>
<% end %>

<footer class = "footer">
  <nav>
		<ul>
		  <li><%= link_to 'Back', recipe_path(@recipe) %></li>
    </ul>
	</nav>
</footer>