config/routes.rb
Rails.application.routes.draw do
  resources :categories
  root 'recipes#index'
  resources :recipes do
    member do
      get :tags
      post :tag_add
      post :tag_remove
    end
  end

  resources :tags do
    member do
      get :recipe_list
    end
  end

  resources :pantry_items do
    member do
      get :tags
      post :tag_add
      post :tag_remove
    end
  end

  resources :meal_plans do
    member do
      post :update_finished
      get :grocery_list
    end
  end

  resources :meal_plan_recipe_items

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/pantry_item.rb
class PantryItem < ApplicationRecord
  validates :name, presence: true, uniqueness: {case_sensitive: false}
  has_and_belongs_to_many :tags
end

app/controllers/pantry_items_controller.rb
class PantryItemsController < ApplicationController
  before_action :set_pantry_item, only: [:show, :edit, :update, :destroy]

  def new
    @pantry_item = PantryItem.new
  end

  def edit
  end

  def show
    redirect_to action: "tags"
  end

  def create
    @pantry_item = PantryItem.new(pantry_item_params)
    if @pantry_item.save
      redirect_to action: "index"
    else
      render 'new'
    end
  end

  def update
    if @pantry_item.update(pantry_item_params)
      redirect_to @pantry_item
    else
      render 'edit'
    end
  end

  def index
    @pantry_items = PantryItem.order("name")
  end

  def tags
    @pantry_item = PantryItem.find(params[:id])
    @tags = @pantry_item.tags.order("name")
  end

  def tag_add
    @pantry_item = PantryItem.find(params[:id])
    tag_ids = params[:tags]

    if tag_ids.any?
      tag_ids.each do |tag_id|
        tag = Tag.find(tag_id)
        logger.info "Adding tag #{tag.id}"
        @pantry_item.tags << tag
      end
    end
    redirect_to action: "tags", id: @pantry_item
  end

  def tag_remove
    @pantry_item = PantryItem.find(params[:id])
    tag_ids = params[:tags]

    if tag_ids.any?
      tag_ids.each do |tag_id|
        tag = Tag.find(tag_id)
        logger.info "Removing tag #{tag.id}"
        @pantry_item.tags.delete(tag)
      end
    end
    redirect_to action: "tags", id: @pantry_item
  end

  private
    def pantry_item_params
      params.require(:pantry_item).permit(:name)
    end

    def set_pantry_item
      @pantry_item = PantryItem.find(params[:id])
    end
end

app/helpers/pantry_items_helper.rb
module PantryItemsHelper
end

app/views/pantry_items/_form.html.erb
<div class = "row">
  <div class = "span6 offset3">
    <br>
    <%= form_for (pantry_item) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>
      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>
      <br><br>
      <%= f.submit button + " Pantry Item", class: "btn btn-large btn-primary"%>
    <% end %>
  </div>
</div>

app/views/pantry_items/edit.html.erb
<h1>Edit Pantry Item</h1>

<%= render 'form', pantry_item: @pantry_item, button: "Update" %>

app/views/pantry_items/index.html.erb
<h1>All Pantry Items</h1>
<%= link_to "New Pantry Item", new_pantry_item_path %>
<br>
<br>

<table class = "table table-bordered">
  <thead>
    <tr>
      <th>Pantry Item</th>
      <th>Tags</th>
    </tr>
  </thead>

  <tbody>
    <% @pantry_items.each do |pantry_item| %>
      <tr>
        <td><%= link_to pantry_item.name, pantry_item %></td>
        <td><%= pantry_item.tags.collect {|c| c.name}.join('<br>').html_safe %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/pantry_items/new.html.erb
<h1>New Pantry Item</h1>

<%= render 'form', pantry_item: @pantry_item, button: "Add" %>

app/views/pantry_items/show.html.erb
<h1>
	<%= @pantry_item.name %>
</h1>

app/views/pantry_items/tags.html.erb
<h1><%= @pantry_item.name %>'s Tags</h1>

<h3>Remove Tags</h3>
<% if @tags.count > 0 then %>
  <%= form_tag (tag_remove_pantry_item_path(@pantry_item)) do %>
    <table>
      <thead>
        <th>Remove?</th>
        <th>Tag</th>
      </thead>
      <tbody>
        <% @tags.each do |tag| %>
          <tr>
            <td><%= check_box_tag "tags[]", tag.id %></td>
            <td><%=tag.name%></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  <br>
  <%= submit_tag "Remove Tag(s)" %>
  <% end %>
<% else %>
  <p>No tags yet</p>
<% end %>

<h3>Add Tags</h3>
<%= form_tag (tag_add_pantry_item_path(@pantry_item)) do %>
  <table>
    <thead>
      <th>Add?</th>
      <th>Tag</th>
    </thead>
    <tbody>
      <% (Tag.all.order("name") - @pantry_item.tags).each do |tag| %>
        <tr>
          <td><%= check_box_tag "tags[]", tag.id %></td>
          <td><%= tag.name %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <br>
  <%= submit_tag "Add Tag(s)" %>
<% end %>