config/routes.rb
Rails.application.routes.draw do
  resources :categories
  root 'recipes#index'
  resources :recipes do
    member do
      get :tags
      post :tag_add
      post :tag_remove
    end
  end

  resources :tags do
    member do
      get :recipe_list
    end
  end

  resources :pantry_items do
    member do
      get :tags
      post :tag_add
      post :tag_remove
    end
  end

  resources :meal_plans do
    member do
      post :update_finished
      get :grocery_list
    end
  end

  resources :meal_plan_recipe_items

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_header.html.erb
<header class="navbar navbar-default navbar-fixed-top">
  <div class="container">
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Meal Plans", meal_plans_path %></li>
        <li><%= link_to "Pantry Items", pantry_items_path %></li>
        <li><%= link_to "Tags", tags_path %></li>
        <li><%= link_to "Recipes", recipes_path %></li>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RecipeApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <%= content_tag(:div,message,class:"alert alert-#{message_type}") %>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>